### ISSUE TITLE
String formating prevents successfull tests

### ISSUE THREAD

**Issue by LoeschMaximilian** [nymea/nymea-remoteproxy#25] opened 2022-02-15 15:15 UTC
Hi,

i am trying to build Debian packages of the tunnel-proxy branch.
Commit: accb6ec166bdb41b494a5cc38c6c4b010c45bcf0
The Dockerfile:
```

FROM debian:buster AS builder
ARG branch=master
RUN apt update && apt install -y qt5-default libqt5websockets5-dev ncurses-dev git g++ make build-essential debhelper pkg-config
RUN git clone --branch=${branch} https://github.com/nymea/nymea-remoteproxy
WORKDIR /nymea-remoteproxy/
RUN dpkg-buildpackage -uc -us
```
Run with:
`docker build --buid-arg branch=tunnel-proxy .`
Gets me these erros:
```
FAIL!  : RemoteProxyTestsProxy::monitorServer() Compared values are not the same
   Actual   (connectionOne->tunnelPartnerUuid()): "721ffe71-c32b-4c89-b4f5-279ea02c5e8b"
   Expected (uuidConnectionTwo.toString())      : "{721ffe71-c32b-4c89-b4f5-279ea02c5e8b}"
   Loc: [remoteproxytestsproxy.cpp(172)]
[...]
FAIL!  : RemoteProxyTestsProxy::authenticateNonce() Compared values are not the same
   Actual   (connectionOne->tunnelPartnerUuid()): "f7359640-ccb0-4dc2-aa5b-de7bb43f3096"
   Expected (uuidConnectionTwo.toString())      : "{f7359640-ccb0-4dc2-aa5b-de7bb43f3096}"
   Loc: [remoteproxytestsproxy.cpp(641)]
[...]
FAIL!  : RemoteProxyTestsProxy::remoteConnection() Compared values are not the same
   Actual   (connectionOne->tunnelPartnerUuid()): "277c3d0a-1243-46a7-8855-f725bf162861"
   Expected (uuidConnectionTwo.toString())      : "{277c3d0a-1243-46a7-8855-f725bf162861}"
   Loc: [remoteproxytestsproxy.cpp(880)]
[...]
FAIL!  : RemoteProxyTestsProxy::tcpRemoteConnection() Compared values are not the same
   Actual   (connectionOne->tunnelPartnerUuid()): "390e3677-2dce-4b7e-9a4a-49609d0abae7"
   Expected (uuidConnectionTwo.toString())      : "{390e3677-2dce-4b7e-9a4a-49609d0abae7}"
   Loc: [remoteproxytestsproxy.cpp(1296)]
[...]
FAIL!  : RemoteProxyTestsProxy::tcpWebsocketRemoteConnection() Compared values are not the same
   Actual   (connectionOne->tunnelPartnerUuid()): "ce9316a6-c9c5-42e8-9b07-ef3fdc24d2d7"
   Expected (uuidConnectionTwo.toString())      : "{ce9316a6-c9c5-42e8-9b07-ef3fdc24d2d7}"
   Loc: [remoteproxytestsproxy.cpp(1390)]
[...]
Totals: 50 passed, 5 failed, 0 skipped, 0 blacklisted, 28686ms
```

**Comment by t-mon** [comment] 2022-02-15 16:25
Thanks for reporting, I almost finished the fix. 

The issue is the different Qt versions, when they started to remove the `{}` from the `QUuid::toString()` method. This is a bug in the tests we have not seen so far because we run the tests against the oldest supported distribution.

**Comment by t-mon** [comment] 2022-02-15 20:51
I pushed the fix already :-)

https://github.com/nymea/nymea-remoteproxy/commit/1c1231a92629efa435a52e0c7138baadce2ad7ba

**Comment by LoeschMaximilian** [comment] 2022-02-15 21:07
Well both solutions fix the issue at hand, which is why i am going to close this issue.

I think the more significant Problem, is that the ProxyConnection Object posses a stringified Copy of UUID that is not the result of a `toString()` call.
This makes the behavior inconsistent and results in such clumsy fixes.
The user should not need to guess that much at the format of the string.
Maybe rather than a String return a Copy of the `QUuid`?
It would also fit the naming of the member functions better.

In which version of the Library were the curly braces removed?
As far as i have seen and read in the documentation the {xx...xx} format is the default and a version of `toString` exists, which gives the option to not include the braces.

**Closed** 2022-02-15 21:07 UTC

**Comment by mzanetti** [comment] 2022-02-15 21:14
> Maybe rather than a String return a Copy of the `QUuid`?
> It would also fit the naming of the member functions better.

Yes. I agree.



> In which version of the Library were the curly braces removed?
> As far as i have seen and read in the documentation the {xx...xx} format is the default and a version of `toString` exists, which gives the option to not include the braces.

IIRC it was Qt 5.12. The `toString()` existed all along, and always returned the UUID including the braces. Starting with 5.12, the implicit conversion to QString changed. The parameter in QUuid::toString() is new with 5.12 too so we can't use it yet as we'll have to keep backwards compatibility with older Qt versions for now.

**Comment by LoeschMaximilian** [comment] 2022-02-15 21:23
`toString()` returning {xx....xx} format is still the default as of 5.15, according to the documentation at [The official Docs](https://doc.qt.io/qt-5/quuid.html#toString)

**Comment by mzanetti** [comment] 2022-02-15 21:41
Ok, I've tracked the issue down to `remoteproxyclient::JsonRpCclient::tunnelProxyClientConnected()` emitting a QUUid but the connected slot (connection in remoteproxyconnection.cpp:345) `RemoteProxyConnection::onTunnelEstablished()` taking a QString. This means, the conversion from QUuid to QString is done by QMetaObject::invokeMethod() and that for some reason seems to lose the braces. 

So yes, the correct solution is to change `RemoteProxyConnection::m_tunnelPartnerUuid` to be a QUuid instead of a QString also return QUuid in related methods, which then will also allow to compare 2 QUuids in the test and this problem never exists.

**Comment by t-mon** [comment] 2022-02-16 06:36
I this section of the proxy (this is not the tunnel proxy), the uuid actually can be any string and is pure informative for both sides of a tunnel. 
The uuid issue show up only in the tests because I used a uuid as identifier for the client and compared both as string. Clients get mached using a share nonce during connection establishment. Meaning: converting the string to a uuid and converting it back to a string on API side is an operation without any point on the proxy side.

**Comment by t-mon** [comment] 2022-02-16 06:42
Fo completeness: In the tunnel proxy on the other hand, it must be a valid Uuid, because client and server get matched using the server uuid. There, all comparisons within the proxy are based on QUuid comparisons, not string, you also get an error if you pass an invalid uuid `TunnelProxyServer::TunnelProxyErrorInvalidUuid`.

**Comment by mzanetti** [comment] 2022-02-16 08:57
It is a Uuid, it also should be a UUID on the API, really... if you convert it inside the lib before handing it out on the API, users of the lib will have to deal with the {} issue, always.

And the fact that currently it's auto-converted by a mismatching signal/slot connection is not nice either. In fact, I think we should disable such auto-conversions which would make the code fail to compile.
